# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift_Learning_App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'AppCenter'
  # Pods for Swift_Learning_App

  target 'Swift_Learning_AppTests' do
    inherit! :search_paths
  end

  target 'Swift_Learning_AppUITests' do
    # Pods for testing
  end

end
